os: linux
dist: xenial

git:
  depth: 1

jobs:
  include:
    - stage: TypeScript
      language: node_js
      cache:
        yarn: true
        directories:
          - node_modules
      script: yarn ci
    - stage: PHP
      language: php
      php: 7.4
      install: composer install
      cache:
        directories:
          - $HOME/.composer/cache
      script: composer phing ci

notifications:
  webhooks:
    - https://coveralls.io/webhook

